services:
  - type: web
    name: reel-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: API_KEY
        value: mysecretkey999